export const categoryList = [
    {
        id:1,
        name:"airpods",
        value:"airpods"
    },
    {
        id:2,
        name:"camera",
        value:"camera"
    },
    {
        id:3,
        name:"earphones",
        value:"earphones"
    },
    {
        id:4,
        name:"mouse",
        value:"mouse"
    },
    {
        id:5,
        name:"printers",
        value:"printers"
    },
    {
        id:6,
        name:"processor",
        value:"processor"
    },
    {
        id:7,
        name:"mobile",
        value:"mobile"
    },
    {
        id:8,
        name:"refrigerator",
        value:"refrigerator"
    },
    {
        id:9,
        name:"speakers",
        value:"speakers"
    },
    {
        id:10,
        name:"TV",
        value:"TV"
    },
    {
        id:11,
        name:"watches",
        value:"watches"
    },


]